"""Generate problem variants by computing the Cartesian product of parameter dimensions."""

import hashlib
import random
from collections import deque
from dataclasses import dataclass
from itertools import product
from typing import Any, Callable


def _stable_hash(name: str) -> int:
    """Deterministic hash that is stable across Python invocations.

    Python's built-in hash() is randomized per process (PYTHONHASHSEED).
    This uses MD5 (truncated to 64 bits) for a stable alternative.
    """
    return int(hashlib.md5(name.encode()).hexdigest(), 16) & 0xFFFFFFFFFFFFFFFF


@dataclass
class VariantDimension:
    """One axis of variation for a problem.

    Attributes:
        name: Parameter name (must match the problem class __init__ kwarg).
        values: List of possible values for this parameter.
    """
    name: str
    values: list[Any]


@dataclass
class VariantSpec:
    """Declares the full parameter space for a problem class.

    Attributes:
        problem_class: The Problem subclass to instantiate.
        base_name: Base problem ID prefix (e.g., "readiness_probe_misconfiguration").
        dimensions: List of VariantDimensions defining the parameter axes.
        constraints: Optional filter function. Receives a dict of param_name->value
                     and returns True if the combination is valid.
        derived_params: Optional function that receives the dimension params dict and
                        returns additional kwargs to pass to the problem constructor.
                        These do not affect the variant ID.
    """
    problem_class: type
    base_name: str
    dimensions: list[VariantDimension]
    constraints: Callable[[dict[str, Any]], bool] | None = None
    derived_params: Callable[[dict[str, Any]], dict[str, Any]] | None = None


def generate_variants(spec: VariantSpec) -> dict[str, Callable]:
    """Generate all valid variant combinations from a spec.

    Computes the Cartesian product of all dimensions, filters by constraints,
    and returns a dict mapping deterministic variant IDs to factory callables.

    The variant ID format is: {base_name}__v_{value1}_{value2}_...
    Values are joined in the order of the dimensions list.

    Args:
        spec: A VariantSpec defining the parameter space.

    Returns:
        Dict mapping variant_id strings to zero-arg callables that produce
        Problem instances.
    """
    if not spec.dimensions:
        return {}

    dim_names = [d.name for d in spec.dimensions]
    dim_values = [d.values for d in spec.dimensions]

    variants = {}
    for combo in product(*dim_values):
        params = dict(zip(dim_names, combo))

        # Apply constraints filter
        if spec.constraints and not spec.constraints(params):
            continue

        # Generate deterministic ID from parameter values
        suffix = "_".join(str(v) for v in combo)
        variant_id = f"{spec.base_name}__v_{suffix}"

        # Merge any derived params (don't affect variant ID)
        captured = dict(params)
        if spec.derived_params:
            captured.update(spec.derived_params(params))
        variants[variant_id] = lambda p=captured: spec.problem_class(**p)

    return variants


def generate_all_variants(specs: list[VariantSpec]) -> dict[str, Callable]:
    """Generate variants from multiple specs, checking for collisions.

    Args:
        specs: List of VariantSpecs.

    Returns:
        Combined dict of all variant_id -> factory mappings.

    Raises:
        ValueError: If two specs produce the same variant ID.
    """
    all_variants = {}
    for spec in specs:
        generated = generate_variants(spec)
        for vid, factory in generated.items():
            if vid in all_variants:
                raise ValueError(
                    f"Variant ID collision: '{vid}' generated by multiple specs"
                )
            all_variants[vid] = factory
    return all_variants


def filter_variant_ids_by_spec(
    variant_ids: list[str],
    spec_names: list[str],
    known_base_names: set[str],
) -> list[str]:
    """Filter variant IDs to those whose spec base_name is in ``spec_names``.

    Args:
        variant_ids: Pool of variant IDs (each containing the ``__v_`` separator).
        spec_names: Spec base_names to keep.
        known_base_names: All valid base_names, used to validate ``spec_names``.

    Returns:
        Subset of ``variant_ids`` whose base_name (text before ``__v_``) is in
        ``spec_names``.

    Raises:
        ValueError: If any name in ``spec_names`` is not in ``known_base_names``.
    """
    unknown = [n for n in spec_names if n not in known_base_names]
    if unknown:
        raise ValueError(
            f"Unknown variant spec name(s): {unknown}. "
            f"Valid names: {sorted(known_base_names)}"
        )
    selected = set(spec_names)
    return [vid for vid in variant_ids if vid.split("__v_")[0] in selected]


def _group_by_class(variant_ids: list[str]) -> dict[str, list[str]]:
    """Group variant IDs by their base_name (problem class).

    Splits each ID on '__v_' and uses the prefix as the group key.
    Within each group, IDs are sorted for determinism.
    """
    groups: dict[str, list[str]] = {}
    for vid in variant_ids:
        base_name = vid.split("__v_")[0]
        groups.setdefault(base_name, []).append(vid)
    for key in groups:
        groups[key].sort()
    return groups


def generate_variant_stream_by_class(
    variant_ids: list[str],
    count: int,
    offset: int = 0,
    seed: int = 42,
) -> list[str]:
    """Generate a deterministic stream interleaved by problem class (round-robin).

    Each "round" picks one variant from every problem class before any class
    gets a second pick. Within each round the class order is shuffled with
    seed (seed + round_number). Within each class the variant order is shuffled
    with a separate per-class seed. When a class exhausts its variants it wraps
    to the next per-class epoch (re-shuffled).

    Args:
        variant_ids: Pool of variant IDs to cycle through.
        count: Number of problems to return.
        offset: Starting position in the stream (default 0).
        seed: Base seed for deterministic shuffling (default 42).

    Returns:
        List of ``count`` variant IDs from the stream starting at ``offset``.

    Raises:
        ValueError: If variant_ids is empty or count <= 0.
    """
    if not variant_ids:
        raise ValueError("variant_ids must not be empty")
    if count <= 0:
        raise ValueError("count must be > 0")

    groups = _group_by_class(variant_ids)
    class_names = sorted(groups.keys())
    num_classes = len(class_names)

    # Pre-build per-class iterators: each tracks its own epoch.
    class_queues: dict[str, list[str]] = {}
    class_epochs: dict[str, int] = {name: 0 for name in class_names}

    def _refill(name: str) -> None:
        """Shuffle and refill the queue for a class using its current epoch."""
        epoch = class_epochs[name]
        # Use a seed that depends on both the class name and epoch
        rng = random.Random(seed + _stable_hash(name) + epoch)
        order = groups[name].copy()
        rng.shuffle(order)
        class_queues[name] = order
        class_epochs[name] = epoch + 1

    for name in class_names:
        _refill(name)

    # Generate the full stream from position 0 up to offset + count,
    # then slice to [offset : offset + count].
    total_needed = offset + count
    result: list[str] = []
    round_num = 0

    while len(result) < total_needed:
        # Shuffle class order for this round
        rng = random.Random(seed + round_num)
        round_order = class_names.copy()
        rng.shuffle(round_order)

        for name in round_order:
            if not class_queues[name]:
                _refill(name)
            result.append(class_queues[name].pop(0))
            if len(result) >= total_needed:
                break

        round_num += 1

    return result[offset:offset + count]


def generate_variant_stream_grouped(
    variant_ids: list[str],
    count: int,
    offset: int = 0,
    seed: int = 42,
    max_per_class: int | None = None,
) -> list[str]:
    """Generate a deterministic stream that drains one class before the next.

    Within each epoch:
      - The class order is shuffled with seed (seed + epoch).
      - Each class's variants are shuffled with a per-class+epoch seed.
      - Up to ``max_per_class`` variants per class are emitted (None = all
        variants in the class).

    When all classes have been drained, a new epoch begins (re-shuffled).
    The epoch size is constant, so ``offset`` is handled by the same
    ``divmod`` trick as ``generate_variant_stream``.

    Args:
        variant_ids: Pool of variant IDs to cycle through.
        count: Number of problems to return.
        offset: Starting position in the stream (default 0).
        seed: Base seed for deterministic shuffling (default 42).
        max_per_class: Optional cap on how many variants to emit per class
            within a single epoch. ``None`` means emit all of them.

    Returns:
        List of ``count`` variant IDs from the stream starting at ``offset``.

    Raises:
        ValueError: If variant_ids is empty, count <= 0, or
            max_per_class is not None and not > 0.
    """
    if not variant_ids:
        raise ValueError("variant_ids must not be empty")
    if count <= 0:
        raise ValueError("count must be > 0")
    if max_per_class is not None and max_per_class <= 0:
        raise ValueError("max_per_class must be > 0 or None")

    groups = _group_by_class(variant_ids)
    class_names = sorted(groups.keys())

    def _per_class_take(name: str) -> int:
        size = len(groups[name])
        return min(size, max_per_class) if max_per_class is not None else size

    epoch_size = sum(_per_class_take(name) for name in class_names)

    start_epoch, start_pos = divmod(offset, epoch_size)
    result: list[str] = []
    epoch = start_epoch
    pos_in_epoch = start_pos

    while len(result) < count:
        # Build this epoch's full sequence deterministically.
        rng = random.Random(seed + epoch)
        round_order = class_names.copy()
        rng.shuffle(round_order)

        epoch_sequence: list[str] = []
        for name in round_order:
            cls_rng = random.Random(seed + _stable_hash(name) + epoch)
            cls_order = groups[name].copy()
            cls_rng.shuffle(cls_order)
            epoch_sequence.extend(cls_order[: _per_class_take(name)])

        take = min(count - len(result), len(epoch_sequence) - pos_in_epoch)
        result.extend(epoch_sequence[pos_in_epoch:pos_in_epoch + take])
        epoch += 1
        pos_in_epoch = 0

    return result


class AdaptiveScheduler:
    """Per-class adaptive scheduler for variant streams.

    Walks problem classes in sorted order. For each class, dispatches variants
    one at a time and tracks pass/fail outcomes. Advances to the next class
    when *either*:

      - The last ``consec_solves_to_stop`` outcomes for the current class are
        all solves (the agent has demonstrated mastery), or
      - ``max_per_class`` total attempts have been made in the current class
        (the budget is spent — give up).

    An optional ``max_total`` cap stops the scheduler once that many problems
    have been dispatched in total across all classes (checked in
    :meth:`next_problem` and :meth:`is_done`).

    Within a class, variants are seeded-shuffled using the same recipe as the
    other variant streams (``seed + _stable_hash(class_name) + epoch``). When a
    class's pool is exhausted before either stop criterion fires, the scheduler
    increments the class epoch and re-shuffles, allowing repeats.

    Each call to :meth:`next_problem` returns a ``(seq_idx, pid)`` tuple where
    ``seq_idx`` is a monotonically increasing counter starting from
    ``start_seq_idx``. ``next_problem`` returns ``None`` once all classes have
    been completed or abandoned (or the global ``max_total`` cap is reached).

    Outcomes are reported via :meth:`record_completion`. The scheduler infers
    the class from the variant ID by splitting on ``__v_``.

    Resume is supported by replaying historical completions in the order they
    happened. The scheduler's "current class" pointer always advances to the
    earliest class that has not yet been completed/abandoned, so a fresh
    instance fed the same completions ends up in the same state.
    """

    def __init__(
        self,
        variant_ids: list[str],
        consec_solves_to_stop: int,
        max_per_class: int,
        seed: int = 42,
        start_seq_idx: int = 0,
        max_total: int | None = None,
    ) -> None:
        if not variant_ids:
            raise ValueError("variant_ids must not be empty")
        if consec_solves_to_stop <= 0:
            raise ValueError("consec_solves_to_stop must be > 0")
        if max_per_class <= 0:
            raise ValueError("max_per_class must be > 0")
        if max_total is not None and max_total <= 0:
            raise ValueError("max_total must be > 0")

        self._seed = seed
        self._consec_solves_to_stop = consec_solves_to_stop
        self._max_per_class = max_per_class
        self._max_total = max_total

        self._groups = _group_by_class(variant_ids)
        self._class_order: list[str] = sorted(self._groups.keys())

        # Per-class state. ``recent`` is a deque of bools (latest at the right);
        # mastery is reached when it is full and all entries are True.
        self._queues: dict[str, list[str]] = {name: [] for name in self._class_order}
        self._epochs: dict[str, int] = {name: 0 for name in self._class_order}
        self._attempts: dict[str, int] = {name: 0 for name in self._class_order}
        self._recent: dict[str, deque[bool]] = {
            name: deque(maxlen=consec_solves_to_stop) for name in self._class_order
        }
        self._done: dict[str, bool] = {name: False for name in self._class_order}

        self._class_idx = 0
        self._next_seq_idx = start_seq_idx

    # -- internal helpers ----------------------------------------------------

    def _refill(self, name: str) -> None:
        """Reshuffle the queue for ``name`` using the next epoch."""
        epoch = self._epochs[name]
        rng = random.Random(self._seed + _stable_hash(name) + epoch)
        order = self._groups[name].copy()
        rng.shuffle(order)
        self._queues[name] = order
        self._epochs[name] = epoch + 1

    def _is_class_done(self, name: str) -> bool:
        if self._done[name]:
            return True
        if self._attempts[name] >= self._max_per_class:
            return True
        recent = self._recent[name]
        return len(recent) == self._consec_solves_to_stop and all(recent)

    def _advance_class(self) -> None:
        """Move ``_class_idx`` past any classes that are now done."""
        while self._class_idx < len(self._class_order):
            name = self._class_order[self._class_idx]
            if self._is_class_done(name):
                self._done[name] = True
                self._class_idx += 1
            else:
                return

    @staticmethod
    def _class_of(pid: str) -> str:
        return pid.split("__v_")[0]

    # -- public API ----------------------------------------------------------

    def next_problem(self) -> tuple[int, str] | None:
        """Return the next ``(seq_idx, pid)`` to dispatch, or ``None`` if all
        classes are exhausted or the global ``max_total`` cap is reached."""
        if self._max_total is not None and self._next_seq_idx >= self._max_total:
            return None
        self._advance_class()
        if self._class_idx >= len(self._class_order):
            return None

        name = self._class_order[self._class_idx]
        if not self._queues[name]:
            self._refill(name)

        pid = self._queues[name].pop(0)
        seq_idx = self._next_seq_idx
        self._next_seq_idx += 1
        return (seq_idx, pid)

    def record_completion(self, pid: str, solved: bool) -> None:
        """Record an outcome and update per-class state."""
        name = self._class_of(pid)
        if name not in self._attempts:
            # Unknown class (shouldn't happen in practice — pid was generated
            # by this scheduler). Ignore silently to keep replay robust.
            return
        self._attempts[name] += 1
        self._recent[name].append(bool(solved))
        if self._is_class_done(name):
            self._done[name] = True

    def is_done(self) -> bool:
        """True if every class has been completed or abandoned, or the global
        ``max_total`` cap has been reached."""
        if self._max_total is not None and self._next_seq_idx >= self._max_total:
            return True
        self._advance_class()
        return self._class_idx >= len(self._class_order)

    @property
    def next_seq_idx(self) -> int:
        return self._next_seq_idx

    def set_next_seq_idx(self, value: int) -> None:
        if value < self._next_seq_idx:
            raise ValueError(
                f"set_next_seq_idx must not go backwards "
                f"(have {self._next_seq_idx}, got {value})"
            )
        self._next_seq_idx = value

    def class_state_summary(self) -> dict[str, dict[str, Any]]:
        """Return a small dict-of-dicts describing per-class progress.

        Useful for logging / debugging.
        """
        return {
            name: {
                "attempts": self._attempts[name],
                "recent_solves": list(self._recent[name]),
                "done": self._done[name],
            }
            for name in self._class_order
        }

    @property
    def class_order(self) -> list[str]:
        return list(self._class_order)


def generate_variant_stream(
    variant_ids: list[str],
    count: int,
    offset: int = 0,
    seed: int = 42,
) -> list[str]:
    """Generate a deterministic stream of variant IDs using epoch-based cycling.

    The stream is logically infinite: epoch k shuffles the sorted variant pool
    with seed (seed + k). The returned list is the slice [offset : offset + count].

    This ensures every variant appears exactly once per epoch before any repeats,
    and the stream is fully deterministic given the same (variant_ids, seed).

    Args:
        variant_ids: Pool of variant IDs to cycle through.
        count: Number of problems to return.
        offset: Starting position in the stream (default 0).
        seed: Base seed for deterministic shuffling (default 42).

    Returns:
        List of ``count`` variant IDs from the stream starting at ``offset``.

    Raises:
        ValueError: If variant_ids is empty or count <= 0.
    """
    if not variant_ids:
        raise ValueError("variant_ids must not be empty")
    if count <= 0:
        raise ValueError("count must be > 0")

    canonical = sorted(variant_ids)
    n = len(canonical)
    result: list[str] = []

    start_epoch, start_pos = divmod(offset, n)
    remaining = count
    epoch = start_epoch

    while remaining > 0:
        rng = random.Random(seed + epoch)
        epoch_order = canonical.copy()
        rng.shuffle(epoch_order)

        start = start_pos if epoch == start_epoch else 0
        take = min(remaining, n - start)
        result.extend(epoch_order[start:start + take])
        remaining -= take
        epoch += 1

    return result
