"""Generate problem variants by computing the Cartesian product of parameter dimensions."""

import random
from dataclasses import dataclass
from itertools import product
from typing import Any, Callable


@dataclass
class VariantDimension:
    """One axis of variation for a problem.

    Attributes:
        name: Parameter name (must match the problem class __init__ kwarg).
        values: List of possible values for this parameter.
    """
    name: str
    values: list[Any]


@dataclass
class VariantSpec:
    """Declares the full parameter space for a problem class.

    Attributes:
        problem_class: The Problem subclass to instantiate.
        base_name: Base problem ID prefix (e.g., "readiness_probe_misconfiguration").
        dimensions: List of VariantDimensions defining the parameter axes.
        constraints: Optional filter function. Receives a dict of param_name->value
                     and returns True if the combination is valid.
        derived_params: Optional function that receives the dimension params dict and
                        returns additional kwargs to pass to the problem constructor.
                        These do not affect the variant ID.
    """
    problem_class: type
    base_name: str
    dimensions: list[VariantDimension]
    constraints: Callable[[dict[str, Any]], bool] | None = None
    derived_params: Callable[[dict[str, Any]], dict[str, Any]] | None = None


def generate_variants(spec: VariantSpec) -> dict[str, Callable]:
    """Generate all valid variant combinations from a spec.

    Computes the Cartesian product of all dimensions, filters by constraints,
    and returns a dict mapping deterministic variant IDs to factory callables.

    The variant ID format is: {base_name}__v_{value1}_{value2}_...
    Values are joined in the order of the dimensions list.

    Args:
        spec: A VariantSpec defining the parameter space.

    Returns:
        Dict mapping variant_id strings to zero-arg callables that produce
        Problem instances.
    """
    if not spec.dimensions:
        return {}

    dim_names = [d.name for d in spec.dimensions]
    dim_values = [d.values for d in spec.dimensions]

    variants = {}
    for combo in product(*dim_values):
        params = dict(zip(dim_names, combo))

        # Apply constraints filter
        if spec.constraints and not spec.constraints(params):
            continue

        # Generate deterministic ID from parameter values
        suffix = "_".join(str(v) for v in combo)
        variant_id = f"{spec.base_name}__v_{suffix}"

        # Merge any derived params (don't affect variant ID)
        captured = dict(params)
        if spec.derived_params:
            captured.update(spec.derived_params(params))
        variants[variant_id] = lambda p=captured: spec.problem_class(**p)

    return variants


def generate_all_variants(specs: list[VariantSpec]) -> dict[str, Callable]:
    """Generate variants from multiple specs, checking for collisions.

    Args:
        specs: List of VariantSpecs.

    Returns:
        Combined dict of all variant_id -> factory mappings.

    Raises:
        ValueError: If two specs produce the same variant ID.
    """
    all_variants = {}
    for spec in specs:
        generated = generate_variants(spec)
        for vid, factory in generated.items():
            if vid in all_variants:
                raise ValueError(
                    f"Variant ID collision: '{vid}' generated by multiple specs"
                )
            all_variants[vid] = factory
    return all_variants


def _group_by_class(variant_ids: list[str]) -> dict[str, list[str]]:
    """Group variant IDs by their base_name (problem class).

    Splits each ID on '__v_' and uses the prefix as the group key.
    Within each group, IDs are sorted for determinism.
    """
    groups: dict[str, list[str]] = {}
    for vid in variant_ids:
        base_name = vid.split("__v_")[0]
        groups.setdefault(base_name, []).append(vid)
    for key in groups:
        groups[key].sort()
    return groups


def generate_variant_stream_by_class(
    variant_ids: list[str],
    count: int,
    offset: int = 0,
    seed: int = 42,
) -> list[str]:
    """Generate a deterministic stream interleaved by problem class (round-robin).

    Each "round" picks one variant from every problem class before any class
    gets a second pick. Within each round the class order is shuffled with
    seed (seed + round_number). Within each class the variant order is shuffled
    with a separate per-class seed. When a class exhausts its variants it wraps
    to the next per-class epoch (re-shuffled).

    Args:
        variant_ids: Pool of variant IDs to cycle through.
        count: Number of problems to return.
        offset: Starting position in the stream (default 0).
        seed: Base seed for deterministic shuffling (default 42).

    Returns:
        List of ``count`` variant IDs from the stream starting at ``offset``.

    Raises:
        ValueError: If variant_ids is empty or count <= 0.
    """
    if not variant_ids:
        raise ValueError("variant_ids must not be empty")
    if count <= 0:
        raise ValueError("count must be > 0")

    groups = _group_by_class(variant_ids)
    class_names = sorted(groups.keys())
    num_classes = len(class_names)

    # Pre-build per-class iterators: each tracks its own epoch.
    class_queues: dict[str, list[str]] = {}
    class_epochs: dict[str, int] = {name: 0 for name in class_names}

    def _refill(name: str) -> None:
        """Shuffle and refill the queue for a class using its current epoch."""
        epoch = class_epochs[name]
        # Use a seed that depends on both the class name and epoch
        rng = random.Random(seed + hash(name) + epoch)
        order = groups[name].copy()
        rng.shuffle(order)
        class_queues[name] = order
        class_epochs[name] = epoch + 1

    for name in class_names:
        _refill(name)

    # Generate the full stream from position 0 up to offset + count,
    # then slice to [offset : offset + count].
    total_needed = offset + count
    result: list[str] = []
    round_num = 0

    while len(result) < total_needed:
        # Shuffle class order for this round
        rng = random.Random(seed + round_num)
        round_order = class_names.copy()
        rng.shuffle(round_order)

        for name in round_order:
            if not class_queues[name]:
                _refill(name)
            result.append(class_queues[name].pop(0))
            if len(result) >= total_needed:
                break

        round_num += 1

    return result[offset:offset + count]


def generate_variant_stream(
    variant_ids: list[str],
    count: int,
    offset: int = 0,
    seed: int = 42,
) -> list[str]:
    """Generate a deterministic stream of variant IDs using epoch-based cycling.

    The stream is logically infinite: epoch k shuffles the sorted variant pool
    with seed (seed + k). The returned list is the slice [offset : offset + count].

    This ensures every variant appears exactly once per epoch before any repeats,
    and the stream is fully deterministic given the same (variant_ids, seed).

    Args:
        variant_ids: Pool of variant IDs to cycle through.
        count: Number of problems to return.
        offset: Starting position in the stream (default 0).
        seed: Base seed for deterministic shuffling (default 42).

    Returns:
        List of ``count`` variant IDs from the stream starting at ``offset``.

    Raises:
        ValueError: If variant_ids is empty or count <= 0.
    """
    if not variant_ids:
        raise ValueError("variant_ids must not be empty")
    if count <= 0:
        raise ValueError("count must be > 0")

    canonical = sorted(variant_ids)
    n = len(canonical)
    result: list[str] = []

    start_epoch, start_pos = divmod(offset, n)
    remaining = count
    epoch = start_epoch

    while remaining > 0:
        rng = random.Random(seed + epoch)
        epoch_order = canonical.copy()
        rng.shuffle(epoch_order)

        start = start_pos if epoch == start_epoch else 0
        take = min(remaining, n - start)
        result.extend(epoch_order[start:start + take])
        remaining -= take
        epoch += 1

    return result
