"""Generate problem variants by computing the Cartesian product of parameter dimensions."""

from dataclasses import dataclass
from itertools import product
from typing import Any, Callable


@dataclass
class VariantDimension:
    """One axis of variation for a problem.

    Attributes:
        name: Parameter name (must match the problem class __init__ kwarg).
        values: List of possible values for this parameter.
    """
    name: str
    values: list[Any]


@dataclass
class VariantSpec:
    """Declares the full parameter space for a problem class.

    Attributes:
        problem_class: The Problem subclass to instantiate.
        base_name: Base problem ID prefix (e.g., "readiness_probe_misconfiguration").
        dimensions: List of VariantDimensions defining the parameter axes.
        constraints: Optional filter function. Receives a dict of param_name->value
                     and returns True if the combination is valid.
    """
    problem_class: type
    base_name: str
    dimensions: list[VariantDimension]
    constraints: Callable[[dict[str, Any]], bool] | None = None


def generate_variants(spec: VariantSpec) -> dict[str, Callable]:
    """Generate all valid variant combinations from a spec.

    Computes the Cartesian product of all dimensions, filters by constraints,
    and returns a dict mapping deterministic variant IDs to factory callables.

    The variant ID format is: {base_name}__v_{value1}_{value2}_...
    Values are joined in the order of the dimensions list.

    Args:
        spec: A VariantSpec defining the parameter space.

    Returns:
        Dict mapping variant_id strings to zero-arg callables that produce
        Problem instances.
    """
    if not spec.dimensions:
        return {}

    dim_names = [d.name for d in spec.dimensions]
    dim_values = [d.values for d in spec.dimensions]

    variants = {}
    for combo in product(*dim_values):
        params = dict(zip(dim_names, combo))

        # Apply constraints filter
        if spec.constraints and not spec.constraints(params):
            continue

        # Generate deterministic ID from parameter values
        suffix = "_".join(str(v) for v in combo)
        variant_id = f"{spec.base_name}__v_{suffix}"

        # Capture params in closure via default argument
        captured = dict(params)
        variants[variant_id] = lambda p=captured: spec.problem_class(**p)

    return variants


def generate_all_variants(specs: list[VariantSpec]) -> dict[str, Callable]:
    """Generate variants from multiple specs, checking for collisions.

    Args:
        specs: List of VariantSpecs.

    Returns:
        Combined dict of all variant_id -> factory mappings.

    Raises:
        ValueError: If two specs produce the same variant ID.
    """
    all_variants = {}
    for spec in specs:
        generated = generate_variants(spec)
        for vid, factory in generated.items():
            if vid in all_variants:
                raise ValueError(
                    f"Variant ID collision: '{vid}' generated by multiple specs"
                )
            all_variants[vid] = factory
    return all_variants
